import Head from "next/head";
import SocketIOClient, { io } from "socket.io-client";
import { useEffect, useState } from "react";
import { useUsername } from "../_app";
import { useRouter } from "next/router";

export default function Chat() {
	const [chat, setChat] = useState<Msg[]>([]);
	const [msg, setMsg] = useState<string>("");
	const { username } = useUsername();
    const router = useRouter();

	type Msg = {
        id: number;
		username: string;
		message: string;
	};

	useEffect((): any => {
		// connect to socket server
		fetch("/api/socket");
		var socket = io({upgrade:false});

        if(username === '' || username === undefined) {
            router.push('/')
        }

		// log socket connection
		socket.on("connect", () => {
			console.log("CONNECTION ESTABLISHED FOR " + socket.id);
        });

        socket.on('allMessages', (chats) => {
            setChat(chats);
        })

		socket.on("newMsg", (msg: Msg) => {
			setChat(prevChat => [...prevChat, msg]);
            socket.emit('newMessages', msg);
		});

		// socket disconnect onUnmount if exists
		if (socket) return () => socket.disconnect();
	}, []);

	const addMsg = async (e: { preventDefault: () => void; }) => {
		e.preventDefault();
		const inputMsg:HTMLInputElement|null = document.querySelector("#InputChat");

		if (msg) {
			// build message obj
			const message: Msg = {
                id: Math.floor(Math.random() * 2000),
				username: username,
				message: msg,
			};

			// dispatch message to other users
			const resp = await fetch("/api/chat", {
				method: "POST",
				headers: {
					"Content-Type": "application/json",
				},
				body: JSON.stringify(message),
			});

			// reset field if OK
			if (resp.ok && inputMsg) {
				setMsg("");
                inputMsg.value = '';
			}
		}
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main id="map" className="w-screen h-screen">
				<>
					{username}
					<form action="" onSubmit={addMsg}>
						<input
							type="text"
							className="border-2 border-black"
							onChange={(e) => setMsg(e.target.value)}
							id="InputChat"
						/>
						<button type="submit">SUBMIT</button>
					</form>
					<div>
						{chat
							? chat.map((msg, msgIndex) => (
									<div key={msgIndex}>
										{msg.username} : {msg.message}
									</div>
							  ))
							: ""}
					</div>
				</>
			</main>
		</>
	);
}
