import Head from "next/head";
import { useUsername } from "./_app";
import { useRouter } from "next/router";

export default function Home() {
	const { username, setUsername } = useUsername();
	const router = useRouter();

	function changeUsername(e: { preventDefault: () => void; }) {
		e.preventDefault();
		const inputUsername: HTMLInputElement | null =
			document.querySelector("#userNameBox");

		if (inputUsername) {
			setUsername(inputUsername.value.trim());
			router.push('/chat');
		}
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main id="map" className="w-screen h-screen">
				<form action="" onSubmit={changeUsername}>
					<input
						id="userNameBox"
						type="text"
						placeholder="change your username"
					/>
					<button type="submit">submit</button>

					{username}
				</form>
			</main>
		</>
	);
}
