import Head from "next/head";
import SocketIOClient, { io } from "socket.io-client";
import { useEffect, useState } from "react";

let players: string[] = [];
export default function Home() {
	useEffect((): any => {
		// connect to socket server
		fetch('/api/socket');
		var socket = io({transports: ['websocket'], upgrade: false});

		// log socket connection
		socket.on("connect", () => {
			console.log('CONNECTION ESTABLISHED FOR ' + socket.id)
		});

		// socket disconnet onUnmount if exists
		if (socket) return () => socket.disconnect();
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main id="map" className="w-screen h-screen">
				{players.map((player, index) => (
					<p key={index}>{player}</p>
				))}
			</main>
		</>
	);
}
